<a href="https://colab.research.google.com/github/Prabin-chaudhary/Concepts-and-Technology-of-AI/blob/main/worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Task 1
import numpy as np
empty_array = np.empty((2, 2))#create empty array
#print array
print(empty_array)

#Task 2
ones_array = np.ones((4, 2))#initialize an all one array
#print ones array
print(ones_array)

#Task 3
new_array = np.full((3,3),9)
#print new array
print(new_array)

#Task 4
given_array = np.array([[4, 5], [6, 7]])#produce an array of shape 2*2
zeros_like_array = np.zeros_like(given_array)#create array filled with zero
#print output
print(zeros_like_array)

#Task 5
ones_like_array = np.ones_like(given_array)#create array filled with one
#print output
print(ones_like_array)


#task6
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)#converts list into array
#print output
print(numpy_array)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


In [3]:
#problem 2
#task1
import numpy as np
arr1 = np.arange(10, 50)
print(arr1)

#task2
arr2 = np.arange(9).reshape(3, 3)
print(arr2)

#task3
arr3 = np.eye(3)
print(arr3)

#task4
arr4 = np.random.random(30)
mean_arr4 = arr4.mean()
print(mean_arr4)


#task5
arr5 = np.random.random((10, 10))
min_val = arr5.min()
max_val = arr5.max()
print("Min value:", min_val)
print("Max value:", max_val)

#task6
arr6 = np.zeros(10)
arr6[4] = 1  # 5th element (index starts from 0)
print(arr6)

#task7
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr7 = arr7[::-1]
print(reversed_arr7)


#task8
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print(arr8)


#task9
arr9 = np.zeros((8, 8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print(arr9)






[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
0.5095136647877005
Min value: 0.009131649718793433
Max value: 0.9585155947355762
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [4]:
#prabolem 3
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_result = x + y
print(add_result)

# 2. Subtract the two arrays
subtract_result = x - y
print(subtract_result)

# 3. Multiply the array with any integers of your choice
multiply_result = x * 2
print(multiply_result)

# 4. Find the square of each element of the array
square_result = np.square(x)
print(square_result)

# 5. Dot product calculations
dot_vw = np.dot(v, w)
print(dot_vw)

dot_xv = np.dot(x, v)
print(dot_xv)

dot_xy = np.dot(x, y)
print(dot_xy)

# 6. Concatenate along row and column
concat_xy_rows = np.concatenate((x, y), axis=0)
print(concat_xy_rows)

v_reshaped = v.reshape(-1, 1)
w_reshaped = w.reshape(-1, 1)
concat_vw_columns = np.concatenate((v_reshaped, w_reshaped), axis=1)
print(concat_vw_columns)

# 7. Concatenate x and v and explain the error
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print(concat_xv)
except Exception as e:
    print(f"Error when concatenating x and v along axis=0: {e}")

try:
    concat_xv = np.concatenate((x, v), axis=1)
    print(concat_xv)
except Exception as e:
    print(f"Error when concatenating x and v along axis=1: {e}")



[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 2  4]
 [ 6 10]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
Error when concatenating x and v along axis=0: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Error when concatenating x and v along axis=1: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [5]:
#problem 4
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.eye(2)
product = np.dot(A, A_inv)
print("A * A^-1:\n", product)
print("Identity matrix:\n", I)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

# 3. Prove (AB)^T = B^T * A^T
AB_transpose = np.transpose(np.dot(A, B))
B_transpose_A_transpose = np.dot(np.transpose(B), np.transpose(A))
print("Transpose of AB:\n", AB_transpose)
print("B^T * A^T:\n", B_transpose_A_transpose)

# Solving the system of equations using the inverse method
A_system = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_system = np.array([-1, -3, 9])
A_inv_system = np.linalg.inv(A_system)
X = np.dot(A_inv_system, B_system)
print("Solution for X, Y, Z:", X)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix:
 [[1. 0.]
 [0. 1.]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Transpose of AB:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Solution for X, Y, Z: [ 2.  1. -2.]


In [ ]:
#problem 5
import time
import numpy as np

# 1. Element-wise Addition

# Using Python Lists
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000001, 2000001)]

start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(1000000)]
end_time = time.time()
list_add_time = end_time - start_time
print(f"Time taken for element-wise addition using Python lists: {list_add_time} seconds")

# Using NumPy Arrays
arr1 = np.arange(1, 1000001)
arr2 = np.arange(1000001, 2000001)

start_time = time.time()
arr_sum = arr1 + arr2
end_time = time.time()
numpy_add_time = end_time - start_time
print(f"Time taken for element-wise addition using NumPy arrays: {numpy_add_time} seconds")


# 2. Element-wise Multiplication

# Using Python Lists
start_time = time.time()
list_mult = [list1[i] * list2[i] for i in range(1000000)]
end_time = time.time()
list_mult_time = end_time - start_time
print(f"Time taken for element-wise multiplication using Python lists: {list_mult_time} seconds")

# Using NumPy Arrays
start_time = time.time()
arr_mult = arr1 * arr2
end_time = time.time()
numpy_mult_time = end_time - start_time
print(f"Time taken for element-wise multiplication using NumPy arrays: {numpy_mult_time} seconds")


# 3. Dot Product

# Using Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(1000000))
end_time = time.time()
dot_product_list_time = end_time - start_time
print(f"Time taken for dot product using Python lists: {dot_product_list_time} seconds")

# Using NumPy Arrays
start_time = time.time()
dot_product_numpy = np.dot(arr1, arr2)
end_time = time.time()
dot_product_numpy_time = end_time - start_time
print(f"Time taken for dot product using NumPy arrays: {dot_product_numpy_time} seconds")


# 4. Matrix Multiplication

# Create two 1000x1000 matrices using Python Lists
matrix1_list = [[i + j for j in range(1000)] for i in range(1000)]
matrix2_list = [[i - j for j in range(1000)] for i in range(1000)]

start_time = time.time()
matrix_mult_list = [[sum(matrix1_list[i][k] * matrix2_list[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
end_time = time.time()
matrix_mult_list_time = end_time - start_time
print(f"Time taken for matrix multiplication using Python lists: {matrix_mult_list_time} seconds")

# Create two 1000x1000 matrices using NumPy Arrays
matrix1_numpy = np.random.rand(1000, 1000)
matrix2_numpy = np.random.rand(1000, 1000)

start_time = time.time()
matrix_mult_numpy = np.dot(matrix1_numpy, matrix2_numpy)
end_time = time.time()
matrix_mult_numpy_time = end_time - start_time
print(f"Time taken for matrix multiplication using NumPy arrays: {matrix_mult_numpy_time} seconds")


Time taken for element-wise addition using Python lists: 0.1531074047088623 seconds
Time taken for element-wise addition using NumPy arrays: 0.0053691864013671875 seconds
Time taken for element-wise multiplication using Python lists: 0.1672067642211914 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.005241870880126953 seconds
Time taken for dot product using Python lists: 0.1434311866760254 seconds
Time taken for dot product using NumPy arrays: 0.001939535140991211 seconds
